# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoadStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadStart.setGeometry(QtCore.QRect(30, 20, 165, 27))
        self.btnLoadStart.setObjectName("btnLoadStart")
        self.btnLoadEnd = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadEnd.setGeometry(QtCore.QRect(430, 20, 158, 27))
        self.btnLoadEnd.setObjectName("btnLoadEnd")
        self.btnBlend = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlend.setGeometry(QtCore.QRect(340, 690, 92, 27))
        self.btnBlend.setObjectName("btnBlend")
        self.sldAlpha = QtWidgets.QSlider(self.centralwidget)
        self.sldAlpha.setGeometry(QtCore.QRect(70, 340, 611, 20))
        self.sldAlpha.setMaximum(20)
        self.sldAlpha.setProperty("value", 0)
        self.sldAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.sldAlpha.setInvertedAppearance(False)
        self.sldAlpha.setInvertedControls(False)
        self.sldAlpha.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sldAlpha.setTickInterval(2)
        self.sldAlpha.setObjectName("sldAlpha")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(320, 300, 121, 22))
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 290, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 360, 21, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 360, 21, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 660, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 290, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.graLeft = QtWidgets.QGraphicsView(self.centralwidget)
        self.graLeft.setGeometry(QtCore.QRect(30, 50, 321, 241))
        self.graLeft.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graLeft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graLeft.setObjectName("graLeft")
        self.graRight = QtWidgets.QGraphicsView(self.centralwidget)
        self.graRight.setGeometry(QtCore.QRect(430, 50, 321, 241))
        self.graRight.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graRight.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graRight.setObjectName("graRight")
        self.graRes = QtWidgets.QGraphicsView(self.centralwidget)
        self.graRes.setGeometry(QtCore.QRect(230, 390, 331, 241))
        self.graRes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graRes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graRes.setObjectName("graRes")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 340, 41, 17))
        self.label_6.setObjectName("label_6")
        self.txtAlpha = QtWidgets.QLabel(self.centralwidget)
        self.txtAlpha.setGeometry(QtCore.QRect(690, 340, 71, 31))
        self.txtAlpha.setFrameShape(QtWidgets.QFrame.Box)
        self.txtAlpha.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtAlpha.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAlpha.setObjectName("txtAlpha")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLoadStart.setText(_translate("MainWindow", "Load Starting Image ..."))
        self.btnLoadEnd.setText(_translate("MainWindow", "Load Ending Image ..."))
        self.btnBlend.setText(_translate("MainWindow", "Blend"))
        self.checkBox.setText(_translate("MainWindow", "Show Triangles"))
        self.label_2.setText(_translate("MainWindow", "Ending Image"))
        self.label_3.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "1.0"))
        self.label_5.setText(_translate("MainWindow", "Blending Result"))
        self.label.setText(_translate("MainWindow", "Starting Image"))
        self.label_6.setText(_translate("MainWindow", "Alpha"))
        self.txtAlpha.setText(_translate("MainWindow", "0.0"))

